// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubqyzjndnamunvsqjutc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicXl6am5kbmFtdW52c3FqdXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODI5NTcsImV4cCI6MjA2ODY1ODk1N30.l0A-J2h48GXfPDZtxnKI_TwisXA_dMIZjY-3TJK6GWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});